### ISSUE TITLE
Error to compile on php:5.6.40-fpm-alpine3.8

### ISSUE THREAD

**Issue by wesleywillians** [elastic/apm-agent-php#81]
Hello guys,

I'm trying to install the apm agent using the php:5.6.40-fpm-alpine3.8 docker image. However, I got the error:

```
/bin/bash /home/apm-agent/apm/src/ext/libtool --mode=compile cc  -I. -I/home/apm-agent/apm/src/ext -DPHP_ATOM_INC -I/home/apm-agent/apm/src/ext/include -I/home/apm-agent/apm/src/ext/main -I/home/apm-agent/apm/src/ext -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/apm-agent/apm/src/ext/ConfigManager.c -o ConfigManager.lo 
mkdir .libs
 cc -I. -I/home/apm-agent/apm/src/ext -DPHP_ATOM_INC -I/home/apm-agent/apm/src/ext/include -I/home/apm-agent/apm/src/ext/main -I/home/apm-agent/apm/src/ext -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/apm-agent/apm/src/ext/ConfigManager.c  -fPIC -DPIC -o .libs/ConfigManager.o
In file included from /home/apm-agent/apm/src/ext/elastic_apm_alloc.h:20:0,
                 from /home/apm-agent/apm/src/ext/ConfigManager.c:25:
/home/apm-agent/apm/src/ext/platform.h:16:38: fatal error: execinfo.h: No such file or directory
 #   include <execinfo.h> // backtrace
                                      ^
compilation terminated.
make: *** [Makefile:181: ConfigManager.lo] Error 1
```

The command I used to install is:
```
RUN mkdir -p /home/apm-agent && \
    cd /home/apm-agent && \
    git clone https://github.com/elastic/apm-agent-php.git apm && \
    cd apm/src/ext && \
    /usr/local/bin/phpize && ./configure --enable-elastic_apm && \
    make clean && make
```

Any Idea?
All the best.

**Comment by SergeyKleyman** [comment]
Hi @wesleywillians 

Thank you for the feedback - it's very valuable!

It seems the issue you've encountered is related to the absence of some dev libraries. According to https://pkgs.alpinelinux.org/contents?file=execinfo.h you need to install `libexecinfo-dev` package on Alpine Linux. I'll make sure docs have an example on how to build the Agent on Alpine Linux.

Also please note the agent supports PHP 7.2 or higher (so PHP 5.* is not supported) - I'll make sure docs mentioned that as well.
