### ISSUE TITLE
Support PHP 8.1

### ISSUE THREAD

**Issue by Sharoff45** [elastic/apm-agent-php#582]
I'm trying to install the agent on PHP 8.1, and apm agent doesn't support this PHP version

Error when compiling:

```
/apm-agent-php/src/ext/util_for_PHP.c: In function 'loadPhpFile':
/apm-agent-php/src/ext/util_for_PHP.c:48:5: warning: passing argument 1 of 'php_stream_open_for_zend_ex' from incompatible pointer type [enabled by default]
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: expected 'struct zend_file_handle *' but argument is of type 'const char *'
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:48:5: warning: passing argument 2 of 'php_stream_open_for_zend_ex' makes integer from pointer without a cast [enabled by default]
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: expected 'int' but argument is of type 'struct zend_file_handle *'
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:48:5: error: too many arguments to function 'php_stream_open_for_zend_ex'
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: declared here
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:65:9: warning: implicit declaration of function 'zend_file_handle_dtor' [-Wimplicit-function-declaration]
         zend_file_handle_dtor( &file_handle );
         ^
make: *** [util_for_PHP.lo] Error 1
```

**Comment by Sharoff45** [comment]
Starts from version PHP 8.1.0 signature of method _php_stream_open_for_zend_ex_ changed to:
`
PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
`

https://github.com/php/php-src/blob/php-8.1.0RC1/main/php_main.h

**Comment by mtl-coder-lch** [comment]
@Sharoff45 I tried to make php apm agent work with php 8.1 and your changes. Basically I did git clone https://github.com/elastic/apm-agent-php.git and replaced the 3 files setup.asciidoc, supported-technologies.asciidoc and util_for_PHP.c  with your files to have the new changes. 

Then I built it from source however I'm getting the following error  Invalid callback \Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::shutdown, class "\Elastic\Apm\Impl\AutoInstrument\PhpPartFacade" not found . This error happens during composer install and I didn't have it before with 8.0, but I was previously using the deb package. 

I'm also getting this warning: /elastic/apm-agent-php/src/ext/util_for_PHP.c: In function 'loadPhpFile':
/elastic/apm-agent-php/src/ext/util_for_PHP.c:70:9: warning: implicit declaration of function 'zend_file_handle_dtor'; did you mean 'zend_iterator_dtor'? [-Wimplicit-function-declaration]
         zend_file_handle_dtor( &file_handle );
         ^~~~~~~~~~~~~~~~~~~~~
         zend_iterator_dtor

Is there something I'm missing?

**Comment by SergeyKleyman** [comment]
Implemented in #604.
Thank you @Sharoff45 for initiating the process :)

**Comment by progmancod** [comment]
> Implemented in #604. Thank you @Sharoff45 for initiating the process :)

Sorry, but I got the same error after this merge.

**Comment by SergeyKleyman** [comment]
@progmancod Could you please provide the following details about your environment:
- [ ] Linux distro type and version
- [ ] PHP version

**Comment by bck01215** [comment]
This occurred on Manjaro and php version ```8.1.5```
